version: '3.8'

services:
    pugbot:
        extends:
            file: docker-compose/common-services.yml
            service: pugbot
        env_file:
            - .env
        volumes:
            - .:/opt/pugbot/
        ports:
            - 5678:5678
        entrypoint: ["python3", "-m", "debugpy", "--listen", "0.0.0.0:5678", "main.py"]

    db:
        extends:
            file: docker-compose/common-services.yml
            service: db
        env_file:
            - .env