version: '3.8'

services:
    pugbot:
        image: pugbot:latest
        restart: on-failure
        build:
            context: ..
            target: dev
        environment:
            MONGO_HOST: db
            MONGO_PORT: 8081
            MONGO_USERNAME: pugbot
            MONGO_PASSWORD: pugbotspasswor

    db:
        image: mongo:4.4-bionic
        restart: on-failure
        environment:
            MONGO_INITDB_ROOT_USERNAME: pugbot
            MONGO_INITDB_ROOT_PASSWORD: pugbotspassword
        ports:
            - 8081