version: '3.8'

services:
    pugbot:
        image: pugbot:latest
        restart: on-failure
        build:
            context: ..
            target: dev
        environment:
            POSTGRES_HOST: db
            POSTGRES_DB: pugbot
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pugbot

    db:
        image: postgres:12
        restart: on-failure
        environment:
            POSTGRES_DB: pugbot
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pugbot
        ports:
            - 5432